// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpejjcsjbfbhgxcvigiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwZWpqY3NqYmZiaGd4Y3ZpZ2l1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDIwODEsImV4cCI6MjA2NDg3ODA4MX0.lelsMgxfhr_vkL5r8sW6UXJzlH8i7a1RchcDDB14HBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);